[package]
name = "ds4-sniffer"
version = "0.1.0"
authors = ["renanmachad <renanmachadopinho@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
# Sua base estável v1.1.2 de controle de hardware
esp-hal = { version = "1.1.2", features = ["unstable", ] }
esp-println = { version = "0.17.0", features = ["esp32", "log-04"] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32"] }
esp-alloc = {version ="0.10.0", features = ["global-allocator"]}
embassy-executor = "0.10.0"
embassy-time = "0.5.1"
esp-radio = { version = "1.0.0-beta.0", default-features = false, features = ["esp32", "esp-now", "unstable", "wifi"] }
esp-rtos = { version = "0.3.0", default-features = false, features = ["esp32", "embassy", "esp-radio"] }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
